CREATE TABLE EMPLOYEE (
  EMP_NUMBER NUMBER(6) CONSTRAINT EMP_NUMBER_PK PRIMARY KEY,
  EMP_FNAME VARCHAR2(20) CONSTRAINT NN_EMP_FNAME NOT NULL,
  EMP_LNAME VARCHAR2(20) CONSTRAINT NN_EMP_LNAME NOT NULL,
  EMP_PHONE NUMBER(15) CONSTRAINT NN_EMP_PHONE NOT NULL,
  EMP_EMAIL VARCHAR2(40) CONSTRAINT NN_EMP_EMAIL NOT NULL,
  EMP_HOUSE VARCHAR2(10) CONSTRAINT NN_EMP_HOUSE NOT NULL,
  EMP_STREET VARCHAR2(30) CONSTRAINT NN_EMP_STREET NOT NULL,
  EMP_CITY VARCHAR2(30) CONSTRAINT NN_EMP_CITY NOT NULL,
  EMP_SUBURB VARCHAR2(30) CONSTRAINT NN_EMP_SUBURB NOT NULL,
  EMP_ZIP VARCHAR2(10) CONSTRAINT NN_EMP_ZIP NOT NULL,
  EMP_DOB DATE CONSTRAINT NN_EMP_DOB NOT NULL,
  EMP_START DATE DEFAULT SYSDATE CONSTRAINT NN_EMP_START NOT NULL,
  EMP_SALARY DECIMAL(19,4) CONSTRAINT NN_EMP_SALARY NOT NULL,
  CONSTRAINT EMP_UI1 UNIQUE(EMP_LNAME, EMP_FNAME),
  CONSTRAINT EMP_CK1 CHECK (EMP_SALARY > 0),
  CONSTRAINT EMP_CK2 CHECK (EMP_START > TO_DATE('01-JAN-2012','DD-MON-YYYY'))
);

CREATE TABLE CUSTOMER (
  CUS_NUMBER NUMBER(6) CONSTRAINT CUS_NUMBER_PK PRIMARY KEY,
  CUS_FNAME VARCHAR2(20) CONSTRAINT NN_CUS_FNAME NOT NULL,
  CUS_LNAME VARCHAR2(20) CONSTRAINT NN_CUS_LNAME NOT NULL,
  CUS_PHONE NUMBER(15) CONSTRAINT NN_CUS_PHONE NOT NULL,
  CUS_EMAIL VARCHAR2(40) CONSTRAINT NN_CUS_EMAIL NOT NULL,
  CUS_HOUSE VARCHAR2(10) CONSTRAINT NN_CUS_HOUSE NOT NULL,
  CUS_STREET VARCHAR2(30) CONSTRAINT NN_CUS_STREET NOT NULL,
  CUS_SUBURB VARCHAR2(30) CONSTRAINT NN_CUS_SUBURB NOT NULL,
  CUS_CITY VARCHAR2(30) CONSTRAINT NN_CUS_CITY NOT NULL,
  CUS_ZIP VARCHAR2(10) CONSTRAINT NN_CUS_ZIP NOT NULL,
  CUS_UPDATED DATE DEFAULT SYSDATE CONSTRAINT NN_CUS_UPDATED NOT NULL,
  CONSTRAINT CUS_UI1 UNIQUE (CUS_LNAME, CUS_FNAME),
  CONSTRAINT CUS_CK1 CHECK (CUS_UPDATED > TO_DATE('01-JAN-2012','DD-MON-YYYY'))
);

CREATE TABLE SUPPLIER (
  SUP_NUMBER NUMBER(6) CONSTRAINT SUP_NUMBER_PK PRIMARY KEY,
  SUP_NAME VARCHAR2(20) CONSTRAINT NN_SUP_NAME NOT NULL,
  SUP_PHONE NUMBER(20) CONSTRAINT NN_SUP_PHONE NOT NULL,
  SUP_EMAIL VARCHAR2(40) CONSTRAINT NN_SUP_EMAIL NOT NULL,
  SUP_BUILDING VARCHAR(20) CONSTRAINT NN_SUP_BUILDING NOT NULL,
  SUP_STREET VARCHAR2(30) CONSTRAINT NN_SUP_STREET NOT NULL,
  SUP_CITY VARCHAR2(30) CONSTRAINT NN_SUP_CITY NOT NULL,
  SUP_ZIP VARCHAR2(10) CONSTRAINT NN_SUP_ZIP NOT NULL,
  SUP_COUNTRY VARCHAR2(30) CONSTRAINT NN_SUP_COUNTRY NOT NULL,
  SUP_CONTACT_NAME VARCHAR2(40),
  SUP_CONTACT_PHONE NUMBER(20),
  SUP_CONTACT_EMAIL VARCHAR2(40),
  CONSTRAINT SUP_UI1 UNIQUE (SUP_NAME, SUP_BUILDING, SUP_STREET)
);

CREATE TABLE DEVICE (
  DVC_CODE VARCHAR2(6) CONSTRAINT DVC_CODE_PK PRIMARY KEY,
  DVC_TYPE VARCHAR2(30) CONSTRAINT NN_DVC_TYPE NOT NULL
);

CREATE TABLE PART (
  PRT_NUMBER NUMBER(6) CONSTRAINT PRT_NUMBER_PK PRIMARY KEY,
  PRT_DESCRIPTION VARCHAR2(30) CONSTRAINT NN_PRT_DESCRIPTION NOT NULL,
  PRT_COSTPRICE DECIMAL(19,4) CONSTRAINT NN_PRT_COSTPRICE NOT NULL,
  PRT_SALEPRICE DECIMAL(19,4) CONSTRAINT NN_PRT_SALEPRICE NOT NULL,
  PRT_STOCK NUMBER(6) DEFAULT 0 CONSTRAINT NN_PRT_STOCK NOT NULL,
  PRT_MINLEVEL NUMBER(3) DEFAULT 0 CONSTRAINT NN_PRT_MIN NOT NULL,
  SUP_NUMBER NUMBER(6) CONSTRAINT NN_PRT_SUP_FK NOT NULL,
  CONSTRAINT PRT_CK1 CHECK (PRT_COSTPRICE > 0),
  CONSTRAINT PRT_CK2 CHECK (PRT_SALEPRICE > PRT_COSTPRICE),
  CONSTRAINT PRT_SUP_FK FOREIGN KEY (SUP_NUMBER) REFERENCES SUPPLIER
);

CREATE TABLE SERVICE (
  SRV_CODE VARCHAR2(6) CONSTRAINT SRV_CODE_PK PRIMARY KEY,
  SRV_TYPE VARCHAR2(50) CONSTRAINT NN_SRV_TYPE NOT NULL
);

CREATE TABLE PERFORMANCE (
  PER_NUMBER NUMBER(6) CONSTRAINT PER_NUMBER_PK PRIMARY KEY,
  SRV_CODE VARCHAR2(6) CONSTRAINT NN_PER_SRV_FK NOT NULL,
  PRT_NUMBER NUMBER(6) CONSTRAINT NN_PER_PRT_FK NOT NULL,
  PER_QUANTITY NUMBER(3) CONSTRAINT NN_PER_QUANTITY NOT NULL,
  CONSTRAINT PER_PRT_FK FOREIGN KEY (PRT_NUMBER) REFERENCES PART,
  CONSTRAINT PER_SRV_FK FOREIGN KEY (SRV_CODE) REFERENCES SERVICE,
  CONSTRAINT PER_CK1 CHECK (PER_QUANTITY > 0)
);

CREATE TABLE REPAIR (
  RPR_NUMBER NUMBER(6) CONSTRAINT RPR_NUMBER_PK PRIMARY KEY,
  CUS_NUMBER NUMBER(6) CONSTRAINT NN_RPR_CUS_FK NOT NULL,
  EMP_NUMBER NUMBER(6) CONSTRAINT NN_RPR_EMP_FK NOT NULL,
  DVC_CODE VARCHAR2(6) CONSTRAINT NN_RPR_DVC_FK NOT NULL,
  RPR_MODEL VARCHAR2(40) CONSTRAINT NN_RPR_MODEL NOT NULL,
  RPR_SERIAL VARCHAR2(40) CONSTRAINT NN_RPR_SERIAL NOT NULL,
  RPR_DATE DATE DEFAULT SYSDATE CONSTRAINT NN_RPR_DATE NOT NULL,
  RPR_DESCRIPTION VARCHAR2(100) CONSTRAINT NN_RPR_DESCRIPTION NOT NULL,
  SRV_CODE VARCHAR2(6) CONSTRAINT NN_RPR_SRV_FK NOT NULL,
  RPR_STATUS VARCHAR2(20) DEFAULT 'NEW' CONSTRAINT NN_RPR_STATUS NOT NULL,
  CONSTRAINT RPR_CUS_FK FOREIGN KEY (CUS_NUMBER) REFERENCES CUSTOMER,
  CONSTRAINT RPR_DVC_FK FOREIGN KEY (DVC_CODE) REFERENCES DEVICE,
  CONSTRAINT RPR_SRV_FK FOREIGN KEY (SRV_CODE) REFERENCES SERVICE,
  CONSTRAINT RPR_EMP_FK FOREIGN KEY (EMP_NUMBER) REFERENCES EMPLOYEE,
  CONSTRAINT RPR_CK1 CHECK (RPR_DATE > TO_DATE('01-JAN-2012','DD-MON-YYYY')),
  CONSTRAINT RPR_CK2 CHECK (RPR_STATUS IN ('NEW', 'UNDER REPAIR', 'COMPLETE'))
);

CREATE TABLE INVOICE (
  INV_NUMBER NUMBER(6) CONSTRAINT INV_NUMBER_PK PRIMARY KEY,
  INV_DATE DATE DEFAULT SYSDATE CONSTRAINT NN_INV_DATE NOT NULL,
  RPR_NUMBER NUMBER(6) CONSTRAINT NN_INV_RPR_FK NOT NULL,
  CONSTRAINT INV_CK1 CHECK (INV_DATE > TO_DATE('01-JAN-2012','DD-MON-YYYY')),
  CONSTRAINT INV_RPR_FK FOREIGN KEY (RPR_NUMBER) REFERENCES REPAIR,
  CONSTRAINT INV_UI1 UNIQUE (RPR_NUMBER)
);

CREATE TABLE LINE (
  INV_NUMBER NUMBER(6) CONSTRAINT NN_INV_LINE_FK NOT NULL,
  PER_NUMBER NUMBER(6) CONSTRAINT NN_LINE_PER_FK NOT NULL,
  LINE_PRICE DECIMAL(19,4) DEFAULT 0 CONSTRAINT NN_LINE_PRICE NOT NULL,
  CONSTRAINT INV_PER_PK PRIMARY KEY (INV_NUMBER, PER_NUMBER),
  CONSTRAINT LINE_INV_FK FOREIGN KEY (INV_NUMBER) REFERENCES INVOICE ON DELETE CASCADE,
  CONSTRAINT LINE_PER_FK FOREIGN KEY (PER_NUMBER) REFERENCES PERFORMANCE
);
